### ISSUE TITLE
FR: allow changing openai URL and port

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [guywaldman/magic-cli#28]
Hi,

Supporting openai's api is good, but allowing to change the base URL and port allows using things like [openrouter](openrouter.ai/) or [litellm proxy](https://docs.litellm.ai/) whoc is even better!

It would allow using anthropic etc right away for those of us that already use LLMs extensively

**Comment by yuankunzhang** [comment]
This is definitely a good thing to have. In the meantime, you can change it by setting the `OPENAI_API_BASE` environment variable ([ref](https://github.com/dongri/openai-api-rs?tab=readme-ov-file#set-openai_api_base-to-environment-variable-optional)).

**Comment by guywaldman** [comment]
Resolved in 0.0.6 (pushed out soon), which adds support for a custom OpenAI endpoint and Anthropic as an LLM provider.

cc @yuankunzhang @thiswillbeyourgithub @Ronbalt
