### ISSUE TITLE
FR: ability to disable embeddings

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [guywaldman/magic-cli#30]
Hi,

I'd like to use OpenAI for ask and suggest but am not comfortable sending my whole shell history to them. There's a non zero chance that I leaked a secret at some point in my history and sending it remotely is not okay with me.

Hence, I think it's reasonnable to add an arg to specify which provider to use for embeddings.

**Comment by guywaldman** [comment]
Hi @thiswillbeyourgithub.
This is great feedback.

I prefer to be safe than sorry, so I think I will go ahead and by default disable embeddings if the provider is non-local LLM unless explicitly configured by the user.

**Comment by guywaldman** [comment]
Resolved in [0.0.5](https://github.com/guywaldman/magic-cli/releases/tag/0.0.5)
